import type { Metadata } from 'next';
import { Inter, Montserrat, Oswald } from 'next/font/google';
import ThemeWrapper from '@/src/theme/ThemeWrapper';
import CssBaseline from '@mui/material/CssBaseline';
import EmotionProvider from './emotion-provider';

const inter = Inter({ subsets: ['latin'] });
const montserrat = Montserrat({ subsets: ['latin'], weight: ['800', '900'] });
const oswald = Oswald({ subsets: ['latin'], weight: ['700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt" suppressHydrationWarning>
      <body className={inter.className}>
        <EmotionProvider>
          <ThemeWrapper>
            <CssBaseline />
            {children}
          </ThemeWrapper>
        </EmotionProvider>
      </body>
    </html>
  );
}
