import ThemeWrapper from "@/theme/ThemeWrapper";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body>
        <AppRouterCacheProvider>
          <ThemeWrapper>
            {children}
          </ThemeWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
